name: Execução de Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'   # Executa às 09:00, 11:00, 15:00 e 18:00 de segunda a sexta-feira

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm run test